// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzqukrihoqsvcdynfkrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6cXVrcmlob3FzdmNkeW5ma3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTkyOTksImV4cCI6MjA3Mzc5NTI5OX0.SDRtNcq5Ex4i5LTX8b3TEfmW8SxeW4w-5gRo3z0JcpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});